/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PollingSystemInterface extends Interface {
    getFunction(nameOrSignature: "MAX_OPTIONS" | "MAX_STRING_LENGTH" | "createPoll" | "declareWinner" | "getAllVoteCounts" | "getPoll" | "getVoteChoice" | "getVoteCount" | "getWinner" | "hasAddressVoted" | "isVotingOpen" | "pollCount" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PollCreated" | "VoteCast" | "WinnerDeclared"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_OPTIONS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_STRING_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'createPoll', values: [string, string[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'declareWinner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllVoteCounts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPoll', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVoteChoice', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getVoteCount', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getWinner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasAddressVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isVotingOpen', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pollCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_OPTIONS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_STRING_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPoll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'declareWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllVoteCounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVoteChoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVoteCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasAddressVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isVotingOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pollCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace PollCreatedEvent {
      export type InputTuple = [pollId: BigNumberish, creator: AddressLike, title: string, options: string[], deadline: BigNumberish];
      export type OutputTuple = [pollId: bigint, creator: string, title: string, options: string[], deadline: bigint];
      export interface OutputObject {pollId: bigint, creator: string, title: string, options: string[], deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [pollId: BigNumberish, voter: AddressLike, optionIndex: BigNumberish];
      export type OutputTuple = [pollId: bigint, voter: string, optionIndex: bigint];
      export interface OutputObject {pollId: bigint, voter: string, optionIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinnerDeclaredEvent {
      export type InputTuple = [pollId: BigNumberish, winningOptionIndex: BigNumberish, winningOption: string, winningVoteCount: BigNumberish, isTie: boolean];
      export type OutputTuple = [pollId: bigint, winningOptionIndex: bigint, winningOption: string, winningVoteCount: bigint, isTie: boolean];
      export interface OutputObject {pollId: bigint, winningOptionIndex: bigint, winningOption: string, winningVoteCount: bigint, isTie: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PollingSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): PollingSystem;
    waitForDeployment(): Promise<this>;

    interface: PollingSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_OPTIONS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_STRING_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createPoll: TypedContractMethod<
      [title: string, options: string[], votingDurationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    declareWinner: TypedContractMethod<
      [pollId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllVoteCounts: TypedContractMethod<
      [pollId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getPoll: TypedContractMethod<
      [pollId: BigNumberish, ],
      [[string, string[], bigint, string, bigint] & {title: string, options: string[], deadline: bigint, creator: string, totalVotes: bigint }],
      'view'
    >
    

    
    getVoteChoice: TypedContractMethod<
      [pollId: BigNumberish, voter: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getVoteCount: TypedContractMethod<
      [pollId: BigNumberish, optionIndex: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getWinner: TypedContractMethod<
      [pollId: BigNumberish, ],
      [[bigint, string, bigint, boolean] & {winningOptionIndex: bigint, winningOption: string, winningVoteCount: bigint, isTie: boolean }],
      'view'
    >
    

    
    hasAddressVoted: TypedContractMethod<
      [pollId: BigNumberish, voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isVotingOpen: TypedContractMethod<
      [pollId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    pollCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [pollId: BigNumberish, optionIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_OPTIONS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_STRING_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createPoll'): TypedContractMethod<
      [title: string, options: string[], votingDurationSeconds: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'declareWinner'): TypedContractMethod<
      [pollId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllVoteCounts'): TypedContractMethod<
      [pollId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPoll'): TypedContractMethod<
      [pollId: BigNumberish, ],
      [[string, string[], bigint, string, bigint] & {title: string, options: string[], deadline: bigint, creator: string, totalVotes: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getVoteChoice'): TypedContractMethod<
      [pollId: BigNumberish, voter: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVoteCount'): TypedContractMethod<
      [pollId: BigNumberish, optionIndex: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWinner'): TypedContractMethod<
      [pollId: BigNumberish, ],
      [[bigint, string, bigint, boolean] & {winningOptionIndex: bigint, winningOption: string, winningVoteCount: bigint, isTie: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'hasAddressVoted'): TypedContractMethod<
      [pollId: BigNumberish, voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isVotingOpen'): TypedContractMethod<
      [pollId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pollCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [pollId: BigNumberish, optionIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PollCreated'): TypedContractEvent<PollCreatedEvent.InputTuple, PollCreatedEvent.OutputTuple, PollCreatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'WinnerDeclared'): TypedContractEvent<WinnerDeclaredEvent.InputTuple, WinnerDeclaredEvent.OutputTuple, WinnerDeclaredEvent.OutputObject>;

    filters: {
      
      'PollCreated(uint256,address,string,string[],uint256)': TypedContractEvent<PollCreatedEvent.InputTuple, PollCreatedEvent.OutputTuple, PollCreatedEvent.OutputObject>;
      PollCreated: TypedContractEvent<PollCreatedEvent.InputTuple, PollCreatedEvent.OutputTuple, PollCreatedEvent.OutputObject>;
    

      'VoteCast(uint256,address,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'WinnerDeclared(uint256,uint256,string,uint256,bool)': TypedContractEvent<WinnerDeclaredEvent.InputTuple, WinnerDeclaredEvent.OutputTuple, WinnerDeclaredEvent.OutputObject>;
      WinnerDeclared: TypedContractEvent<WinnerDeclaredEvent.InputTuple, WinnerDeclaredEvent.OutputTuple, WinnerDeclaredEvent.OutputObject>;
    
    };
  }